language: node_js
node_js:
- '6.11.5'
cache:
  yarn: true
  directories:
  - node_modules
before_install: yarn global add greenkeeper-lockfile@1
before_script:
- echo "exporting dummy AWS keys"
- export AWS_ACCESS_KEY_ID=foo
- export AWS_SECRET_ACCESS_KEY=bar
- greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
- yarn lint
- yarn test:coverage
- cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
env:
  global:
  - secure: DBq9gNdehJRTGehHT0dvdvdZDmAt1akA2/dRhi1agwJ5CzQXX7k+g5DmQ8AlkglsoPlZgp6LHOSLQ90gJCsAy5H40+DrNSIHF+9/oPHrDKbVYbiSoAKmQqgVZdvfDvmcnCxKGXea5eh9Tlc1aAIJrSzVctcvyiYHER24de2kmfUx6xUaT1rQBdYAgOhsdZ3/ox5w3aKljTSayq50MjZq8WktpkdbGKIUOM1SH/MRuTLD9ffqXUNCMff425r9UxX/nWPsoVK9s9hTO+RPz6IRcndoi3G/NFmi0zHZBjb+NR+PHxFguAbOCr5Y68DUNm1EA0me9ErKjFquiZxHn/F96TUbcnjDVSfgEp+6I58rFpjCpaeUautSCk2HVjeLqUGZbGdXtAfwiEh9j6o1jtrK30cljc43FlitpT2fz4br8hmQ+ae3saPbX4UyskNOtojkDAYz5cCC1XB7t/AnwCAz1hVPRuZ3ljatLF8h0NSaLDL9weDRhPrd/TO5+33cIAhkv8Z3vkqeQ3GEIBjH/1Ysu0QeF7iUjW7yl6DyPnlQCEqSD3mR8eGsu8wnkeHrmplfXrg1l1THYFsfwweMmoDsLww4Pxz7ZMt18efv3YcdxcETvpC8kdBRCcCw9uOarkgN5Gu6Lryiun5rrlpwsgOb7Ps0hZBm7rnZD4VFCTu/65I=
  - secure: hZpOOWYn7iSrFGwUxB2MiC3Yi3gzixLpTwVTWDZagwopGYfmdUx0+h8o+Cs91jgJFCKF2wyrYqItHtw3szt1NgPtCFnZkZv6JM4JXKXHLU82B9VYWsSwBK9FQBC9UqlqN+OdxtXrTEN2M7BpoTs844YnlgN/K1uTBQPCTt2xAFQjnf45clSQnG4b0RLdd0Kn9kYfJkbt4HCKzJdESHJ6Q5c7B5RZl20Iyyb1UdZBxRmgY+Qp/ZqSQoSDBDH5tf4PF1azxbd3xJk/ujA6rEIa680vFZziNJyN5vUyiEW5OjHfoT87fE1iwI+0IXsst18fsmvbs8flADKSSjnJzQN8StHgXclBhFHWsXAozcuXul0aWzPKUkejrpxVuw4C6zZmdNHGYU08Yuh1x5kgzblCrcLFnpsw0L3bvBRONvdSqk9an8eQHZOLDhdJRJvHmppU7tO/nA+RbUmp/k3Tx3qJr45oPc5NNOfBOj7qb6e+KxEwLwYB6ZSNcDyQ2+rN6CZvuk28R5yCjwkJOh0C7MWkIbOoctSRkanJ6Bq2QBip7xJVsMT1bnoMSfyWGdFH7Trdv8NgWRiHx3N8rFHx22aUduig+MUq1dxidV7MV4JcUXaReEqoNYqY6egvnNO0+1mRuamU+oUfQQrsjoASyq4Jk9DNZuM625yKwzd9e9wTRS8=
